FROM jupyter/pyspark-notebook

# Set the working directory
WORKDIR /app
# Install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the training script and data files
COPY train.py /app/train.py

COPY  customer_churn-1.csv /app/customer_churn-1.csv
RUN  mkdir -p model  temp
RUN chmod -R 777 model  temp
# Set the entrypoint to run the training script
ENTRYPOINT ["python", "train.py"]
